## Importação de arquivos e bibliotecas

In [1]:
# Importação bibliotecas
import pandas as pd

In [2]:
# Importação das bases

df_produtos = pd.read_csv(r'data\raw\produtos_raw.csv')

df_vendas = pd.read_csv(r'data\raw\vendas_2023_2024.csv')

df_clientes = pd.read_json(r'data\raw\clientes_crm.json')

df_custos_importacao =  pd.read_json(r'data\raw\custos_importacao.json')

## Produtos

In [3]:
df_produtos.head()

                             name        price  code        actual_category
0     Transponder AIS Maré Magnum  R$ 33122.52     1            ELETRONICOS
1       Transponder Furuno Marlin  R$ 13998.15     2            ELETRONICOS
2    Radar Furuno Pulse Leviathan   R$ 9024.19     3  E L E T R Ô N I C O S
3       Rádio AIS Hydro Tidal Zen   R$ 3381.88     4            Eletrunicos
4  Piloto Automático Furuno Storm  R$ 23669.01     5            Eletronicoz

In [4]:
df_produtos.shape

(157, 4)

In [5]:
df_produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    object
 1   price            157 non-null    object
 2   code             157 non-null    int64
 3   actual_category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

In [6]:
df_produtos.dtypes

name               object
price              object
code                int64
actual_category    object
dtype: object

## Vendas

In [21]:
df_vendas.head()

   id  id_client  id_product  qtd     total   sale_date
0   0         42         105   11    3405.0  2023-09-10
1   1          3         136    9   16873.9  15-09-2024
2   2         25         139    7    9475.3  2024-08-13
3   4         20          23    5   55893.0  2023-02-03
4   5          8          57    4  451403.9  2024-02-12

In [8]:
df_vendas.shape

(9895, 6)

In [23]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9895 non-null   int64
 1   id_client   9895 non-null   int64
 2   id_product  9895 non-null   int64
 3   qtd         9895 non-null   int64
 4   total       9895 non-null   float64
 5   sale_date   9895 non-null   object
dtypes: float64(1), int64(4), object(1)
memory usage: 464.0+ KB

In [24]:
df_vendas.dtypes

id              int64
id_client       int64
id_product      int64
qtd             int64
total         float64
sale_date      object
dtype: object

In [25]:
df_vendas.columns

Index(['id', 'id_client', 'id_product', 'qtd', 'total', 'sale_date'], dtype='object')

## Clientes

In [11]:
df_clientes.head()

,full_name,location,code,email
0,Femininos Oliveira Antunes,"Aratu (Candeias) , BA",1,femininos.oliveira.antunes@icloud.com
1,Fernanda Azevedo Soares Nunes Vieira,"PE , Recife",2,nunes.fernanda.soares.azevedo.vieira@outlook.com
2,Daniel Farias Ribeiro Teixeira,"Rio Grande,RS",3,farias.teixeira.daniel.ribeiro#gmail.com
3,Thiago Moreira,"AC , Rio Branco",4,thiago.moreira#gmail.com
4,Pedro Freitas,PA - Santarém Novo,5,pedro.freitas#icloud.com

In [12]:
df_clientes.shape

(49, 4)

In [13]:
df_clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   full_name  49 non-null     object
 1   location   49 non-null     object
 2   code       49 non-null     int64
 3   email      49 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.7+ KB

In [14]:
df_clientes.dtypes

full_name    object
location     object
code          int64
email        object
dtype: object

## Custos Importação

In [15]:
df_custos_importacao.head()

,product_id,product_name,category,historic_data
0,1,Transponder AIS Maré Magnum,eletrônicos,"[{'start_date': '10/08/2016', 'usd_price': 105..."
1,2,Transponder Furuno Marlin,eletrônicos,"[{'start_date': '23/11/2017', 'usd_price': 432..."
2,3,Radar Furuno Pulse Leviathan,eletrônicos,"[{'start_date': '12/04/2016', 'usd_price': 254..."
3,4,Rádio AIS Hydro Tidal Zen,eletrônicos,"[{'start_date': '04/03/2016', 'usd_price': 909..."
4,5,Piloto Automático Furuno Storm,eletrônicos,"[{'start_date': '10/02/2016', 'usd_price': 600..."

In [16]:
df_custos_importacao.shape

(150, 4)

In [17]:
df_custos_importacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     150 non-null    int64
 1   product_name   150 non-null    object
 2   category       150 non-null    object
 3   historic_data  150 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

In [18]:
df_custos_importacao.dtypes

product_id        int64
product_name     object
category         object
historic_data    object
dtype: object